spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: "맑은눈의광인메인프로젝트"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420