spring:
  config:
    import: application-dev.yml #설정추가
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql
  output:
    ansi:
      enabled: DETECT
logging:
  level:
    root: INFO
    org.apache: WARN
    org.springframework:
      orm:
        jpa: DEBUG
    org.springframework.boot.devtools: INFO
    org.kurento: INFO
    org.kurento.tutorial: INFO